FROM python:3.8.13

# TODO - add all the necessary to run the script populate_db.py in this image
# 1. Copy the requirements.txt file to the image
# 2. Install the dependencies
# 3. Copy the content of the current directory to the image
# 4. Run the populate_db.py script

# Usa la imagen base de Python 3.8.13
FROM python:3.8.13

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# 1. Copia el archivo de dependencias dentro del contenedor
COPY requirements.txt .

# 2. Instala las dependencias necesarias
RUN pip install --no-cache-dir -r requirements.txt

# 3. Copia todos los archivos del directorio actual al contenedor
COPY . .

# 4. Ejecuta el script para poblar la base de datos
CMD ["python", "populate_db.py"]
